apiVersion: v1
kind: ConfigMap
metadata:
  name: config-map-demo
  labels:
    "spring.cloud.kubernetes.config": "true"
data:
  a: a value from config
  config.property: value for config prop from kubernetes
